# Generated by Django 2.2.6 on 2020-08-08 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UNIAFRIKA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.TextField(max_length=30)),
                ('subject_name', models.TextField(max_length=30)),
                ('date_created', models.DateField(verbose_name=datetime.datetime(2020, 8, 8, 15, 53, 13, 331381, tzinfo=utc))),
                ('challenges', models.TextField(max_length=30)),
                ('improvement', models.TextField(max_length=50)),
                ('projection', models.TextField(max_length=30)),
                ('attitude', models.TextField(max_length=30)),
                ('excecution', models.TextField(max_length=30)),
                ('ability', models.TextField(max_length=30)),
                ('instructor_name', models.TextField(max_length=30)),
                ('instructor_comment', models.TextField(max_length=30)),
                ('comment_to_instructor', models.TextField(max_length=30)),
                ('comment_to_parent', models.TextField(max_length=30)),
            ],
        ),
    ]
