# Generated by Django 2.2.6 on 2020-08-08 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniafrika',
            name='Class',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uniafrika',
            name='topic_treated',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='uniafrika',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 8, 20, 55, 52, 858885, tzinfo=utc)),
        ),
    ]
