# Generated by Django 2.2.6 on 2020-08-08 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20200808_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniafrika',
            old_name='excecution',
            new_name='execution',
        ),
        migrations.AlterField(
            model_name='uniafrika',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 8, 21, 4, 38, 634094, tzinfo=utc)),
        ),
    ]
