# Generated by Django 2.2.6 on 2020-08-09 23:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_auto_20200808_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniafrika',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 9, 23, 11, 32, 937924, tzinfo=utc)),
        ),
    ]
