# Generated by Django 2.2.6 on 2020-08-26 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0004_auto_20200810_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniafrika',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 26, 13, 56, 56, 662489, tzinfo=utc)),
        ),
    ]
