# Generated by Django 2.2.6 on 2020-08-26 14:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0005_auto_20200826_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniafrika',
            name='date_created',
            field=models.DateField(verbose_name=datetime.datetime(2020, 8, 26, 14, 39, 33, 773615, tzinfo=utc)),
        ),
    ]
